### Tokenizer

In [111]:
import os 
import urllib.request

if not os.path.exists("the-verdict.txt"):
    url = ("https://github.com/rasbt/LLMs-from-scratch/tree/main/ch02/01_main-chapter-code")
    file_path = "the-verdict.txt"
    urllib.request.urlretrieve(url,file_path)

In [112]:
with open("the-verdict.txt","r",encoding="utf-8") as f:
    raw_text = f.read()

In [113]:
len(raw_text)

20479

In [114]:
import re
text = "Hello world. This is a test!."
result = re.split(r'([,.!]|\s)',text)
print(result)

['Hello', ' ', 'world', '.', '', ' ', 'This', ' ', 'is', ' ', 'a', ' ', 'test', '!', '', '.', '']


In [115]:
text = "Hello world. This is a test!."
result = re.split(r'([,.!]|\s)',text)
result = [item.strip() for item in result if item.strip()]
print(result)

['Hello', 'world', '.', 'This', 'is', 'a', 'test', '!', '.']


In [116]:
text = raw_text
result = re.split(r'([,.:;?_!"()\']|--|\s)',text)
result = [item.strip() for item in result if item.strip()]
print(result)
preprocessed = result

['I', 'HAD', 'always', 'thought', 'Jack', 'Gisburn', 'rather', 'a', 'cheap', 'genius', '--', 'though', 'a', 'good', 'fellow', 'enough', '--', 'so', 'it', 'was', 'no', 'great', 'surprise', 'to', 'me', 'to', 'hear', 'that', ',', 'in', 'the', 'height', 'of', 'his', 'glory', ',', 'he', 'had', 'dropped', 'his', 'painting', ',', 'married', 'a', 'rich', 'widow', ',', 'and', 'established', 'himself', 'in', 'a', 'villa', 'on', 'the', 'Riviera', '.', '(', 'Though', 'I', 'rather', 'thought', 'it', 'would', 'have', 'been', 'Rome', 'or', 'Florence', '.', ')', '"', 'The', 'height', 'of', 'his', 'glory', '"', '--', 'that', 'was', 'what', 'the', 'women', 'called', 'it', '.', 'I', 'can', 'hear', 'Mrs', '.', 'Gideon', 'Thwing', '--', 'his', 'last', 'Chicago', 'sitter', '--', 'deploring', 'his', 'unaccountable', 'abdication', '.', '"', 'Of', 'course', 'it', "'", 's', 'going', 'to', 'send', 'the', 'value', 'of', 'my', 'picture', "'", 'way', 'up', ';', 'but', 'I', 'don', "'", 't', 'think', 'of', 'that', ',

In [117]:
len(preprocessed)

4690

In [118]:
all_words = sorted(set(preprocessed))
vocab_size = len(all_words)
print(vocab_size)

1130


In [119]:
vocab = {token:integer for integer,token in enumerate(all_words)}

In [124]:
 class SimpleTokenizerV1:
    def __init__(self, vocab):
         self.str_to_int = vocab
         self.int_to_str = {i:s for s,i in vocab.items()}

    def encode(self, text):
        preprocessed = re.split(r'([,.:;?_!"()\']|--|\s)', text)
        
        preprocessed = [item.strip() for item in preprocessed if item.strip()]
        ids = [self.str_to_int[s] for s in preprocessed]
        return ids

    def decode(self, ids):
        text = " ".join([self.int_to_str[i] for i in ids])
        text = re.sub(r'\s+([,.?!"()\'])',r'\1', text)
        return text
       

In [125]:
tokenizer = SimpleTokenizerV1(vocab)

In [126]:
text = """"It's the last he painted, you know," 
            Mrs. Gisburn said with pardonable pride."""

In [128]:
ids = tokenizer.encode(text)
print(ids)

[1, 56, 2, 850, 988, 602, 533, 746, 5, 1126, 596, 5, 1, 67, 7, 38, 851, 1108, 754, 793, 7]


In [129]:
tokenizer.decode(ids)

'" It\' s the last he painted, you know," Mrs. Gisburn said with pardonable pride.'

In [130]:
all_tokens = sorted(list(set(preprocessed)))
all_tokens.extend(["<endoftext>","<|unk|>"])
vocab = {token:integer for integer, token in enumerate(all_tokens)}

In [132]:
len(vocab)

1132

In [147]:
for value, item in enumerate(list(vocab.items())[5]):
    print(item)


,
5


In [154]:
 class SimpleTokenizerV2:
    def __init__(self, vocab):
         self.str_to_int = vocab
         self.int_to_str = {i:s for s,i in vocab.items()}

    def encode(self, text):
        preprocessed = re.split(r'([,.:;?_!"()\']|--|\s)', text)
        
        preprocessed = [item.strip() for item in preprocessed if item.strip()]

        preprocessed = [
            item if item in self.str_to_int
            else "<|unk|>" for item in preprocessed
        ]
        
        ids = [self.str_to_int[s] for s in preprocessed]
        return ids

    def decode(self, ids):
        text = " ".join([self.int_to_str[i] for i in ids])
        text = re.sub(r'\s+([,.?!"()\'])',r'\1', text)
        return text
       

In [155]:
tokenizer = SimpleTokenizerV2(vocab)

In [156]:
text_V2 ="""" Hello It's the last he painted, you know," 
            Mrs. Gisburn said with pardonable pride. Coffee"""

In [158]:
tokenizer.decode(tokenizer.encode(text_V2))

'" <|unk|> It\' s the last he painted, you know," Mrs. Gisburn said with pardonable pride. <|unk|>'

### Byte pair Encoding

In [160]:
import tiktoken

In [162]:
tiktoken.__version__

'0.12.0'

In [163]:
tokenizer = tiktoken.get_encoding("gpt2")

In [164]:
tokenizer.encode("Hello world")

[15496, 995]

In [165]:
tokenizer.decode(tokenizer.encode("Hello world"))

'Hello world'

In [169]:
text ="""" Hello, how are you? It's the last he painted, you know," 
            Mrs. Gisburn said with pardonable pride. Coffee is good for health?"""
tokenizer.encode(text)

[1,
 18435,
 11,
 703,
 389,
 345,
 30,
 632,
 338,
 262,
 938,
 339,
 13055,
 11,
 345,
 760,
 553,
 220,
 198,
 220,
 220,
 220,
 220,
 220,
 220,
 220,
 220,
 220,
 220,
 220,
 9074,
 13,
 402,
 271,
 10899,
 531,
 351,
 27322,
 540,
 11293,
 13,
 19443,
 318,
 922,
 329,
 1535,
 30]

In [171]:
text ="""" Hello, how are you? <|endoftext|>It's the last he painted, you know," 
            Mrs. Gisburn said with pardonable pride. Coffee is good for health?"""
tokenizer.encode(text, allowed_special = {"<|endoftext|>"}) # end of text is not added in tiktokenizer by default

[1,
 18435,
 11,
 703,
 389,
 345,
 30,
 220,
 50256,
 1026,
 338,
 262,
 938,
 339,
 13055,
 11,
 345,
 760,
 553,
 220,
 198,
 220,
 220,
 220,
 220,
 220,
 220,
 220,
 220,
 220,
 220,
 220,
 9074,
 13,
 402,
 271,
 10899,
 531,
 351,
 27322,
 540,
 11293,
 13,
 19443,
 318,
 922,
 329,
 1535,
 30]

### Data Sampling

In [192]:
with open("the-verdict.txt", "r", encoding = "utf-8") as f:
    raw_text = f.read()
enc_text = tokenizer.encode(raw_text)
print(len(enc_text))

5145


In [195]:
enc_sample = enc_text[50:] # Trimming the first 50 tokens/words

In [180]:
context_size = 4
# Aim to predict the next word in a sentence
x = enc_sample[:context_size] # input
y = enc_sample[1:context_size+1]  # target

print(f"x: {x}")
print(f"y:      {y}")

x: [290, 4920, 2241, 287]
y:      [4920, 2241, 287, 257]


In [205]:
 for i in range(1 , len(x)+1):
     input_data = x[:i]
     prediction_data = y[i-1]
     print(f" For input: {input_data} output should be {prediction_data}")
     input_char = tokenizer.decode(x[:i])
     prediction_char = tokenizer.decode([y[i-1]])
     print(f" For input: {input_char} output should be {prediction_char}")


 For input: [290] output should be 4920
 For input:  and output should be  established
 For input: [290, 4920] output should be 2241
 For input:  and established output should be  himself
 For input: [290, 4920, 2241] output should be 287
 For input:  and established himself output should be  in
 For input: [290, 4920, 2241, 287] output should be 257
 For input:  and established himself in output should be  a


In [208]:
import torch

In [209]:
torch.__version__

'2.11.0+cpu'

In [230]:
from torch.utils.data import Dataset, DataLoader

class GPTDatasetV1(Dataset):
    def __init__ (self,txt,tokenizer,max_length,stride):
        self.input_ids = []
        self.target_ids = []

        token_ids = tokenizer.encode(txt, allowed_special = {"|<endoftext>|"})
        assert len(token_ids) > max_length, "No. of token ids less than max_length"

        for i in range(0,len(token_ids),stride):
            input_chunk = token_ids[i:i+max_length]
            target_chunk = token_ids[i+stride:i+max_length+stride]
            self.input_ids.append(torch.tensor(input_chunk)) 
            self.target_ids.append(torch.tensor(target_chunk))

    def __len__(self):
        return len(self.input_ids)

    def __getitem__(self,idx):
        return self.input_ids[idx], self.target_ids[idx]
            
    

In [224]:
def create_dataloader_v1(txt,batch_size=4,max_length=256,
                         stride=128,shuffle=True,drop_last=True,
                        num_workers=0):
    # Get the tokenizer as did previously
    tokenizer = tiktoken.get_encoding("gpt2")

    #Perform the data sampling using GPTDatasetV1 and get in a tensor form
    dataset = GPTDatasetV1(txt,tokenizer,max_length,stride)
    
    dataloader = DataLoader(
        dataset,
    batch_size = batch_size,
    shuffle = shuffle,
    drop_last = drop_last,
    num_workers = num_workers)

    return dataloader

In [221]:
with open("the-verdict.txt", "r", encoding = "utf-8") as f:
    raw_text = f.read()
    

In [235]:
dataloader = create_dataloader_v1(
    raw_text,batch_size=1,max_length=4,stride=1,shuffle=False)

data_iter = iter(dataloader)
first_batch = next(data_iter)
print(first_batch)

[tensor([[  40,  367, 2885, 1464]]), tensor([[ 367, 2885, 1464, 1807]])]


In [234]:
second_batch = (next(data_iter))
print(second_batch)

[tensor([[1807, 3619,  402,  271]]), tensor([[10899,  2138,   257,  7026]])]


In [238]:
dataloader = create_dataloader_v1(
    raw_text,batch_size=8,max_length=4,stride=4,shuffle=False)

data_iter = iter(dataloader)
inputs,targets = next(data_iter)
print("Inputs:\n", inputs)
print("Targets:\n", targets)

Inputs:
 tensor([[   40,   367,  2885,  1464],
        [ 1807,  3619,   402,   271],
        [10899,  2138,   257,  7026],
        [15632,   438,  2016,   257],
        [  922,  5891,  1576,   438],
        [  568,   340,   373,   645],
        [ 1049,  5975,   284,   502],
        [  284,  3285,   326,    11]])
Targets:
 tensor([[ 1807,  3619,   402,   271],
        [10899,  2138,   257,  7026],
        [15632,   438,  2016,   257],
        [  922,  5891,  1576,   438],
        [  568,   340,   373,   645],
        [ 1049,  5975,   284,   502],
        [  284,  3285,   326,    11],
        [  287,   262,  6001,   286]])


### Token Embeddings

In [240]:
input_ids = torch.tensor([2,3,4,5])

In [243]:
vocab_size = 6
output_dim = 3

torch.manual_seed(123) # Initialise the seeding to get the same result
embedding_layer = torch.nn.Embedding(vocab_size,output_dim)

In [244]:
print(embedding_layer.weight)

Parameter containing:
tensor([[ 0.3374, -0.1778, -0.1690],
        [ 0.9178,  1.5810,  1.3010],
        [ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-1.1589,  0.3255, -0.6315],
        [-2.8400, -0.7849, -1.4096]], requires_grad=True)


In [246]:
embedding_layer(torch.tensor([2]))

tensor([[ 1.2753, -0.2010, -0.1606]], grad_fn=<EmbeddingBackward0>)

In [247]:
embedding_layer(input_ids)

tensor([[ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-1.1589,  0.3255, -0.6315],
        [-2.8400, -0.7849, -1.4096]], grad_fn=<EmbeddingBackward0>)

In [248]:
torch.manual_seed(123) # Initialise the seeding to get the same result
embedding_layer = torch.nn.Embedding(tokenizer.n_vocab,output_dim)

In [249]:
print(embedding_layer.weight)

Parameter containing:
tensor([[ 0.3374, -0.1778, -0.3035],
        [-0.5880,  0.3486,  0.6603],
        [-0.2196, -0.3792,  0.7671],
        ...,
        [-0.5931,  1.0895, -0.6854],
        [ 0.7447,  0.5803, -0.4246],
        [-0.3130,  0.7558, -1.2656]], requires_grad=True)


In [250]:
len(embedding_layer.weight)

50257

### Encoding word position

In [251]:
vocab_size = 50257
output_dim = 256

embedding_layer = torch.nn.Embedding(vocab_size,output_dim)

In [253]:
max_length=4
dataloader = create_dataloader_v1(
    raw_text,batch_size=8,max_length=max_length,stride=max_length,shuffle=False)

data_iter = iter(dataloader)
inputs,targets = next(data_iter)


In [254]:
print("Token ids:\n", inputs)
print("Inputs:\n", inputs.shape)


Token ids:
 tensor([[   40,   367,  2885,  1464],
        [ 1807,  3619,   402,   271],
        [10899,  2138,   257,  7026],
        [15632,   438,  2016,   257],
        [  922,  5891,  1576,   438],
        [  568,   340,   373,   645],
        [ 1049,  5975,   284,   502],
        [  284,  3285,   326,    11]])
Inputs:
 torch.Size([8, 4])


In [255]:
token_embeddings = embedding_layer(inputs)
token_embeddings.shape

torch.Size([8, 4, 256])

In [269]:
# Position Embedding
context_len = max_length
pos_embedding_layer = torch.nn.Embedding(context_len,output_dim)
torch.arange(context_len)

tensor([0, 1, 2, 3])

In [270]:
pos_embeddings = pos_embedding_layer(torch.arange(context_len))

In [271]:
print(pos_embeddings.shape)

torch.Size([4, 256])


In [273]:
#Adding token and positon embeeding to add position information to embedding
input_embeddings = token_embeddings + pos_embeddings

In [274]:
print(input_embeddings.shape)

torch.Size([8, 4, 256])
